apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-configuration
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops/cluster-config
    repoURL: 'https://github.com/bhsingh1/cloud-native-deployment-strategies.git'
    targetRevision: HEAD
    helm:
     parameters:
      - name: "bluegreen.enabled"
        value: "true"
      - name: "github.token"
        value: "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"
      - name: "github.user"
        value: "bhsingh1"
      - name: "github.mail"
        value: "bhsingh@redhat.com"
      - name: "github.repository"
        value: "cloud-native-deployment-strategies"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
